projects:
  vocutrainer:
    schemaPath: amplify/backend/api/vocutrainer/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - ./src/graphql/generated/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/generated/API.ts
        docsFilePath: src/graphql/generated
        region: eu-central-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
